#ifndef BLOCK_H_GUARD
#define BLOCK_H_GUARD

#include "BlockMaps.h"

const char *BlockName(uint32_t id, uint32_t data = 0);
const char *BlockStateName(uint32_t id, uint32_t data = 0);

enum BiomeID {
	BIOME_UNKNOWN = -2,
	BIOME_UNCALCULATED = -1,
	BIOME_OCEAN = 0,
	BIOME_PLAINS = 1,
	BIOME_DESERT = 2,
	BIOME_EXTREME_HILLS = 3,
	BIOME_FOREST = 4,
	BIOME_TAIGA = 5,
	BIOME_SWAMPLAND = 6,
	BIOME_RIVER = 7,
	BIOME_NETHER = 8,
	BIOME_END = 9,
	BIOME_FROZEN_OCEAN = 10,
	BIOME_FROZEN_RIVER = 11,
	BIOME_ICE_PLAINS = 12,
	BIOME_ICE_MOUNTAINS = 13,
	BIOME_MUSHROOM_ISLAND = 14,
	BIOME_MUSHROOM_ISLAND_SHORE = 15,
	BIOME_BEACH = 16,
	BIOME_DESERT_HILLS = 17,
	BIOME_FOREST_HILLS = 18,
	BIOME_TAIGA_HILLS = 19,
	BIOME_EXTREME_HILLS_EDGE = 20,
	BIOME_JUNGLE = 21,
	BIOME_JUNGLE_HILLS = 22,
	BIOME_JUNGLE_EDGE = 23,
	BIOME_DEEP_OCEAN = 24,
	BIOME_STONE_BEACH = 25,
	BIOME_COLD_BEACH = 26,
	BIOME_BIRCH_FOREST = 27,
	BIOME_BIRCH_FOREST_HILLS = 28,
	BIOME_ROOFED_FOREST = 29,
	BIOME_COLD_TAIGA = 30,
	BIOME_COLD_TAIGA_HILLS = 31,
	BIOME_MEGA_TAIGA = 32,
	BIOME_MEGA_TAIGA_HILLS = 33,
	BIOME_EXTREME_HILLS_PLUS = 34,
	BIOME_SAVANA = 35,
	BIOME_SAVANA_PLATEAU = 36,
	BIOME_MESA = 37,
	BIOME_MESA_PLATEAU_F = 38,
	BIOME_MESA_PLATEAU = 39,
	// gap in biomes
	BIOME_SUNFLOWER_PLAINS = 129,
	BIOME_DESERT_M = 130,
	BIOME_EXTREME_HILLS_M = 131,
	BIOME_FLOWER_FOREST = 132,
	BIOME_TAIGA_M = 133,
	BIOME_SWAMPLAND_M = 134,
	BIOME_ICE_PLAINS_SPIKES = 140,
	BIOME_JUNGLE_M = 149,
	BIOME_JUNGLE_EDGE_M = 151,
	BIOME_BIRCH_FOREST_M = 155,
	BIOME_BIRCH_FOREST_HILLS_M = 156,
	BIOME_ROOFED_FOREST_M = 157,
	BIOME_COLD_TAIGA_M = 158,
	BIOME_MEGA_SPRUCE_TAIGA = 160,
	BIOME_REDWOOD_TAIGA_HILLS_M = 161,
	BIOME_EXTREME_HILLS_PLUS_M = 162,
	BIOME_SAVANA_M = 163,
	BIOME_SAVANA_PLATEAU_M = 164,
	BIOME_MESA_BRYCE = 165,
	BIOME_MESA_PLATEAU_F_M = 166,
	BIOME_MESA_PLATEAU_M = 167,
	BIOME_LAST = BIOME_MESA_PLATEAU_M
};

const char *BiomeName(BiomeID id);

#endif /* BLOCK_H_GUARD */
